repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.2.0
    hooks:
      - id: mypy
        args: ["--config-file", "mypy.ini"]
        # remova env daqui, pre-commit reclama

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.3
    hooks:
      - id: isort

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.4  # ou a versão mais recente
    hooks:
      - id: ruff
        args: ["--fix", "--max-line-length=120"]
